name: Epic-YYDS
 
on:
  workflow_dispatch:
  schedule:
   # 定时执行可参考https://tool.lu/crontab
    - cron: 22 6 */3 * *
 
jobs:
  setup:
    env:
      EPIC_EMAIL: ${{ secrets.EPIC_EMAIL }}
      EPIC_PASSWORD: ${{ secrets.EPIC_PASSWORD }}
      PUSHER_TELEGRAM: ${{ secrets.PUSHER_TELEGRAM }}
      PLAYER: ${{ secrets.EPIC_PLAYER }}
    runs-on: ubuntu-latest
    steps:
      - name: Docker run
        run: |
          docker run --rm --pull always --init \
          -e EPIC_EMAIL \
		  -e RUN_ON_STARTUP=true \
		  -e BASE_URL=https://store.epicgames.com/zh-CN/ \
          -e EPIC_PASSWORD \
          -m 2g ghcr.io/claabs/epicgames-freegames-node:latest
